from __future__ import annotations


MARKETING_NODES = [
    {
        "id": "node_spring_festival",
        "name": "春节",
        "type": "festival",
        "keywords": ["新春", "团圆", "健康水"],
        "colors": ["#C62828", "#F9D976"],
        "copy_direction": "新春祝福、健康饮水",
        "visual_direction": "红金喜庆氛围",
        "background_asset_id": "asset_bg_spring_festival",
    },
    {
        "id": "node_lantern_festival",
        "name": "元宵",
        "type": "festival",
        "keywords": ["团圆", "灯火", "安心饮水"],
        "colors": ["#B91C1C", "#FFE4B5"],
        "copy_direction": "团圆时刻、安心饮水",
        "visual_direction": "灯火团圆、暖色节庆",
        "background_asset_id": "asset_bg_lantern_festival",
    },
    {
        "id": "node_lichun",
        "name": "立春",
        "type": "solar_term",
        "keywords": ["春日", "焕新", "健康水"],
        "colors": ["#2E7D32", "#D8F3DC"],
        "copy_direction": "春日焕新、健康启程",
        "visual_direction": "清新绿色、春日生长",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_lidong",
        "name": "立冬",
        "type": "solar_term",
        "keywords": ["冬日", "温暖", "健康水"],
        "colors": ["#D98A3B", "#F5E7D2"],
        "copy_direction": "温暖陪伴、健康饮水",
        "visual_direction": "暖色冬日氛围",
        "background_asset_id": "asset_bg_lidong",
    },
    {
        "id": "node_dongzhi",
        "name": "冬至",
        "type": "solar_term",
        "keywords": ["冬至", "团圆", "温暖守护"],
        "colors": ["#1D4ED8", "#F8FAFC"],
        "copy_direction": "冬至团圆、温暖守护",
        "visual_direction": "蓝白冬日、温暖光感",
        "background_asset_id": "asset_bg_dongzhi",
    },
    {
        "id": "node_mid_autumn",
        "name": "中秋",
        "type": "festival",
        "keywords": ["中秋", "团圆", "好水相伴"],
        "colors": ["#8B5E34", "#F6D365"],
        "copy_direction": "团圆佳节、好水相伴",
        "visual_direction": "月色团圆、金色质感",
        "background_asset_id": "asset_bg_mid_autumn",
    },
    {
        "id": "node_national_day",
        "name": "国庆",
        "type": "festival",
        "keywords": ["国庆", "欢庆", "健康生活"],
        "colors": ["#DC2626", "#FACC15"],
        "copy_direction": "欢庆假期、健康生活",
        "visual_direction": "红金庆典、明亮大气",
        "background_asset_id": "asset_bg_national_day",
    },
    {
        "id": "node_double_11",
        "name": "双11",
        "type": "promotion",
        "keywords": ["双11", "咨询", "智能净水"],
        "colors": ["#EF4444", "#FFEDD5"],
        "copy_direction": "节日咨询、智能净水方案",
        "visual_direction": "橙红促销、克制高级",
        "background_asset_id": "asset_bg_double_11",
    },
    {
        "id": "node_618",
        "name": "618",
        "type": "promotion",
        "keywords": ["618", "焕新", "净水方案"],
        "colors": ["#2563EB", "#DBEAFE"],
        "copy_direction": "年中焕新、净水方案咨询",
        "visual_direction": "科技蓝、清爽促销",
        "background_asset_id": "asset_bg_618",
    },
    {
        "id": "node_anniversary",
        "name": "周年庆",
        "type": "campaign",
        "keywords": ["周年", "感谢", "健康水专家"],
        "colors": ["#047857", "#FDE68A"],
        "copy_direction": "品牌感谢、健康水专家",
        "visual_direction": "环保绿、金色庆典",
        "background_asset_id": "asset_bg_anniversary",
    },
]


EXTRA_MARKETING_NODES = [
    {
        "id": "node_qingming",
        "name": "清明",
        "type": "festival",
        "keywords": ["清明", "踏青", "青团", "春雨", "追思"],
        "colors": ["#2F855A", "#E8F5E9"],
        "copy_direction": "清明踏青、春日健康饮水",
        "visual_direction": "春雨新绿、克制清雅、踏青氛围",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_chongyang",
        "name": "重阳",
        "type": "festival",
        "keywords": ["重阳", "敬老", "菊花", "登高", "长辈关怀"],
        "colors": ["#B7791F", "#FFF7ED"],
        "copy_direction": "重阳敬老、健康陪伴、温暖关怀",
        "visual_direction": "秋日暖金、菊花、登高、长辈关怀",
        "background_asset_id": "asset_bg_mid_autumn",
    },
    {
        "id": "node_laba",
        "name": "腊八",
        "type": "festival",
        "keywords": ["腊八", "腊八粥", "冬日", "暖饮"],
        "colors": ["#8B1E3F", "#FDEBD0"],
        "copy_direction": "腊八暖意、健康饮水",
        "visual_direction": "冬日暖色、粥香、家庭餐桌",
        "background_asset_id": "asset_bg_lidong",
    },
    {
        "id": "node_xiaonian",
        "name": "小年",
        "type": "festival",
        "keywords": ["小年", "扫尘", "年味", "新春"],
        "colors": ["#B91C1C", "#FDE68A"],
        "copy_direction": "小年纳福、健康饮水",
        "visual_direction": "红金年味、家居焕新、温暖灯火",
        "background_asset_id": "asset_bg_spring_festival",
    },
    {
        "id": "node_dragon_boat",
        "name": "端午",
        "type": "festival",
        "keywords": ["端午", "粽子", "粽叶", "龙舟", "艾草"],
        "colors": ["#047857", "#DCFCE7"],
        "copy_direction": "端午安康、清润好水",
        "visual_direction": "粽叶青绿、水波、艾草、清爽节日",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_qixi",
        "name": "七夕",
        "type": "festival",
        "keywords": ["七夕", "鹊桥", "浪漫", "星空"],
        "colors": ["#7C3AED", "#FCE7F3"],
        "copy_direction": "七夕陪伴、温柔生活",
        "visual_direction": "星空、花束、温柔光感、克制浪漫",
        "background_asset_id": "asset_bg_mid_autumn",
    },
    {
        "id": "node_new_year_day",
        "name": "元旦",
        "type": "festival",
        "keywords": ["元旦", "新年", "跨年", "焕新"],
        "colors": ["#1D4ED8", "#F8FAFC"],
        "copy_direction": "元旦焕新、健康启程",
        "visual_direction": "明亮焕新、城市灯光、清爽高级",
        "background_asset_id": "asset_bg_dongzhi",
    },
    {
        "id": "node_labor_day",
        "name": "劳动节",
        "type": "festival",
        "keywords": ["五一", "劳动节", "假期", "出游"],
        "colors": ["#DC2626", "#FEF3C7"],
        "copy_direction": "五一假期、健康生活",
        "visual_direction": "明亮假日、城市与家庭生活、轻松氛围",
        "background_asset_id": "asset_bg_national_day",
    },
    {
        "id": "node_teacher_day",
        "name": "教师节",
        "type": "festival",
        "keywords": ["教师节", "老师", "感恩", "讲台"],
        "colors": ["#2563EB", "#E0F2FE"],
        "copy_direction": "教师节感恩、健康陪伴",
        "visual_direction": "书桌、花束、温柔蓝白、感恩氛围",
        "background_asset_id": "asset_bg_618",
    },
    {
        "id": "node_mothers_day",
        "name": "母亲节",
        "type": "festival",
        "keywords": ["母亲节", "妈妈", "鲜花", "陪伴"],
        "colors": ["#DB2777", "#FCE7F3"],
        "copy_direction": "母亲节关怀、健康陪伴",
        "visual_direction": "康乃馨、家庭客厅、柔和暖光",
        "background_asset_id": "asset_bg_mid_autumn",
    },
    {
        "id": "node_fathers_day",
        "name": "父亲节",
        "type": "festival",
        "keywords": ["父亲节", "爸爸", "陪伴", "家庭"],
        "colors": ["#1E40AF", "#E0F2FE"],
        "copy_direction": "父亲节关怀、健康陪伴",
        "visual_direction": "沉稳蓝色、家庭空间、温暖陪伴",
        "background_asset_id": "asset_bg_618",
    },
    {
        "id": "node_yushui",
        "name": "雨水",
        "type": "solar_term",
        "keywords": ["雨水", "春雨", "滋润", "新芽"],
        "colors": ["#0E7490", "#ECFEFF"],
        "copy_direction": "雨水润物、健康饮水",
        "visual_direction": "春雨、水滴、新芽、清润氛围",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_jingzhe",
        "name": "惊蛰",
        "type": "solar_term",
        "keywords": ["惊蛰", "春雷", "万物苏醒", "新生"],
        "colors": ["#15803D", "#DCFCE7"],
        "copy_direction": "惊蛰新生、健康启程",
        "visual_direction": "春雷、嫩芽、自然生长、清新绿色",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_chunfen",
        "name": "春分",
        "type": "solar_term",
        "keywords": ["春分", "花开", "昼夜平分", "春日"],
        "colors": ["#16A34A", "#F0FDF4"],
        "copy_direction": "春分好时光、健康饮水",
        "visual_direction": "春花、阳光、平衡构图、清新自然",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_guyu",
        "name": "谷雨",
        "type": "solar_term",
        "keywords": ["谷雨", "雨生百谷", "茶", "春水"],
        "colors": ["#047857", "#ECFDF5"],
        "copy_direction": "谷雨春水、健康饮水",
        "visual_direction": "茶叶、春雨、谷物、清润绿色",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_lixia",
        "name": "立夏",
        "type": "solar_term",
        "keywords": ["立夏", "夏日", "清凉", "绿荫"],
        "colors": ["#0D9488", "#CCFBF1"],
        "copy_direction": "立夏清润、健康饮水",
        "visual_direction": "绿荫、夏日光影、清凉水感",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_xiaoman",
        "name": "小满",
        "type": "solar_term",
        "keywords": ["小满", "麦穗", "充盈", "初夏"],
        "colors": ["#A16207", "#FEF9C3"],
        "copy_direction": "小满初盈、健康好水",
        "visual_direction": "麦穗、初夏阳光、自然金绿",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_mangzhong",
        "name": "芒种",
        "type": "solar_term",
        "keywords": ["芒种", "麦浪", "耕种", "忙碌"],
        "colors": ["#CA8A04", "#FEF3C7"],
        "copy_direction": "芒种忙碌、清润补给",
        "visual_direction": "麦浪、田野、明亮夏日",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_xiazhi",
        "name": "夏至",
        "type": "solar_term",
        "keywords": ["夏至", "盛夏", "清凉", "荷叶"],
        "colors": ["#059669", "#D1FAE5"],
        "copy_direction": "夏至清凉、健康饮水",
        "visual_direction": "荷叶、水波、盛夏阳光、清爽绿",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_xiaoshu",
        "name": "小暑",
        "type": "solar_term",
        "keywords": ["小暑", "暑气", "清凉", "荷花"],
        "colors": ["#0F766E", "#CCFBF1"],
        "copy_direction": "小暑清润、健康饮水",
        "visual_direction": "荷花、清水、夏日微风",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_dashu",
        "name": "大暑",
        "type": "solar_term",
        "keywords": ["大暑", "盛夏", "消暑", "清凉"],
        "colors": ["#0891B2", "#CFFAFE"],
        "copy_direction": "大暑消暑、清润好水",
        "visual_direction": "冰感水波、夏日光线、清凉蓝绿",
        "background_asset_id": "asset_bg_618",
    },
    {
        "id": "node_liqiu",
        "name": "立秋",
        "type": "solar_term",
        "keywords": ["立秋", "秋意", "桂花", "金色"],
        "colors": ["#B45309", "#FEF3C7"],
        "copy_direction": "立秋润燥、健康饮水",
        "visual_direction": "初秋金色、桂花、温润光感",
        "background_asset_id": "asset_bg_mid_autumn",
    },
    {
        "id": "node_chushu",
        "name": "处暑",
        "type": "solar_term",
        "keywords": ["处暑", "暑退", "秋凉", "清爽"],
        "colors": ["#A16207", "#FFFBEB"],
        "copy_direction": "处暑清凉、健康饮水",
        "visual_direction": "暑气渐退、秋日微风、清爽金绿",
        "background_asset_id": "asset_bg_mid_autumn",
    },
    {
        "id": "node_bailu",
        "name": "白露",
        "type": "solar_term",
        "keywords": ["白露", "露珠", "秋意", "清润"],
        "colors": ["#475569", "#F8FAFC"],
        "copy_direction": "白露清润、健康饮水",
        "visual_direction": "露珠、清晨、淡雅秋色",
        "background_asset_id": "asset_bg_dongzhi",
    },
    {
        "id": "node_qiufen",
        "name": "秋分",
        "type": "solar_term",
        "keywords": ["秋分", "丰收", "金秋", "平衡"],
        "colors": ["#B45309", "#FEF3C7"],
        "copy_direction": "秋分丰盈、健康陪伴",
        "visual_direction": "金秋丰收、麦穗、温暖平衡构图",
        "background_asset_id": "asset_bg_mid_autumn",
    },
    {
        "id": "node_hanlu",
        "name": "寒露",
        "type": "solar_term",
        "keywords": ["寒露", "深秋", "露水", "暖意"],
        "colors": ["#7C2D12", "#FFF7ED"],
        "copy_direction": "寒露添暖、健康饮水",
        "visual_direction": "深秋暖光、露水、茶水间温暖",
        "background_asset_id": "asset_bg_mid_autumn",
    },
    {
        "id": "node_shuangjiang",
        "name": "霜降",
        "type": "solar_term",
        "keywords": ["霜降", "霜叶", "深秋", "暖饮"],
        "colors": ["#9A3412", "#F8FAFC"],
        "copy_direction": "霜降暖饮、健康陪伴",
        "visual_direction": "霜叶、深秋、冷暖对比、温润室内",
        "background_asset_id": "asset_bg_lidong",
    },
    {
        "id": "node_xiaoxue",
        "name": "小雪",
        "type": "solar_term",
        "keywords": ["小雪", "初雪", "暖饮", "冬日"],
        "colors": ["#1E3A8A", "#F8FAFC"],
        "copy_direction": "小雪初至、温暖饮水",
        "visual_direction": "初雪、蓝白冬日、室内暖光",
        "background_asset_id": "asset_bg_dongzhi",
    },
    {
        "id": "node_daxue",
        "name": "大雪",
        "type": "solar_term",
        "keywords": ["大雪", "雪景", "暖意", "冬日"],
        "colors": ["#1D4ED8", "#EFF6FF"],
        "copy_direction": "大雪暖意、健康饮水",
        "visual_direction": "雪景、室内暖光、蓝白高级",
        "background_asset_id": "asset_bg_dongzhi",
    },
    {
        "id": "node_xiaohan",
        "name": "小寒",
        "type": "solar_term",
        "keywords": ["小寒", "寒冬", "暖饮", "守护"],
        "colors": ["#334155", "#F8FAFC"],
        "copy_direction": "小寒守护、温暖饮水",
        "visual_direction": "寒冬、暖光、室内饮水场景",
        "background_asset_id": "asset_bg_dongzhi",
    },
    {
        "id": "node_dahan",
        "name": "大寒",
        "type": "solar_term",
        "keywords": ["大寒", "严冬", "温暖", "守护"],
        "colors": ["#1E293B", "#E2E8F0"],
        "copy_direction": "大寒暖护、健康饮水",
        "visual_direction": "严冬蓝灰、室内暖光、温暖守护",
        "background_asset_id": "asset_bg_dongzhi",
    },
]

MARKETING_NODES.extend(EXTRA_MARKETING_NODES)


PRODUCTS = [
    {
        "id": "product_k2",
        "name": "名士K2智能直饮机",
        "model": "K2",
        "category": "商务直饮机",
        "short_description": "适合办公场景的智能直饮设备",
        "selling_points": ["智能直饮", "适配办公", "稳定供水"],
    },
    {
        "id": "product_h5",
        "name": "名士H5商务直饮机",
        "model": "H5",
        "category": "商务直饮机",
        "short_description": "适合会议、茶水间和公共办公区的商务饮水设备",
        "selling_points": ["商务场景", "多人饮水", "简洁易用"],
    },
    {
        "id": "product_p2",
        "name": "厨下净水器P2",
        "model": "P2",
        "category": "厨下净水器",
        "short_description": "适合家庭厨房的厨下净水解决方案",
        "selling_points": ["厨下安装", "家庭饮水", "日常烹饪"],
    },
]


COMPLIANCE_RULES = {
    "blocked_terms": [
        "最",
        "第一",
        "顶级",
        "绝对",
        "100%",
        "永久",
        "包治",
        "治愈",
        "疗效",
        "神效",
        "唯一",
        "国家级",
        "无敌",
        "根治",
    ],
    "suggestions": {
        "最": "建议改为“更”或删除绝对化表达",
        "第一": "建议改为“领先”并补充真实来源",
        "顶级": "建议改为“高品质”",
        "绝对": "建议改为“持续”或删除",
        "100%": "建议改为“充分”或给出可验证依据",
        "永久": "建议改为“长期”",
        "包治": "不得使用医疗功效承诺",
        "治愈": "不得使用医疗功效承诺",
        "疗效": "不得使用医疗功效暗示",
        "神效": "不得使用夸大功效表达",
        "唯一": "建议改为“可选”或删除",
        "国家级": "不得使用未经证明的权威背书",
        "无敌": "建议删除夸张化表达",
        "根治": "不得使用医疗功效承诺",
    },
}


SYSTEM_ASSET_SOURCES = [
    {
        "id": "asset_logo_original",
        "asset_type": "logo",
        "name": "PUDOW朴道原色Logo",
        "source": "system",
        "source_path": "素材/朴道logo/PUDOW朴道-原色.png",
        "file_name": "logo_original.png",
        "tags": ["PUDOW", "原色"],
    },
    {
        "id": "asset_logo_white",
        "asset_type": "logo",
        "name": "PUDOW朴道反白Logo",
        "source": "system",
        "source_path": "素材/朴道logo/PUDOW朴道-反白.png",
        "file_name": "logo_white.png",
        "tags": ["PUDOW", "反白"],
    },
    {
        "id": "asset_qrcode_wechat",
        "asset_type": "qrcode",
        "name": "朴道公众号二维码",
        "source": "system",
        "source_path": "素材/二维码汇总/朴道公众号二维码.jpg",
        "file_name": "qrcode_wechat.jpg",
        "tags": ["公众号"],
    },
    {
        "id": "asset_qrcode_video",
        "asset_type": "qrcode",
        "name": "朴道官方视频号二维码",
        "source": "system",
        "source_path": "素材/二维码汇总/朴道官方视频号二维码.png",
        "file_name": "qrcode_video.png",
        "tags": ["视频号"],
    },
    {
        "id": "asset_bottom_default",
        "asset_type": "bottom_bar",
        "name": "默认底部宣传条",
        "source": "system",
        "source_path": "素材/asset/素材整理/节日节气海报/底部宣传图.jpg",
        "file_name": "bottom_bar_default.jpg",
        "tags": ["默认", "品牌"],
    },
]


BACKGROUND_SOURCES = [
    {
        "id": "asset_bg_spring_festival",
        "name": "春节背景",
        "source_path": "素材/节日节气海报/除夕海报.jpg",
        "file_name": "bg_spring_festival.jpg",
        "tags": ["春节", "红金"],
    },
    {
        "id": "asset_bg_lantern_festival",
        "name": "元宵背景",
        "source_path": "素材/节日节气海报/元旦海报.jpg",
        "file_name": "bg_lantern_festival.jpg",
        "tags": ["元宵", "节庆"],
    },
    {
        "id": "asset_bg_lichun",
        "name": "立春背景",
        "source_path": "素材/节日节气海报/小满节气海报.jpg",
        "file_name": "bg_lichun.jpg",
        "tags": ["立春", "绿色"],
    },
    {
        "id": "asset_bg_lidong",
        "name": "立冬背景",
        "source_path": "素材/节日节气海报/端午2.jpg",
        "file_name": "bg_lidong.jpg",
        "tags": ["立冬", "暖色"],
    },
    {
        "id": "asset_bg_dongzhi",
        "name": "冬至背景",
        "source_path": "素材/节日节气海报/元旦海报.jpg",
        "file_name": "bg_dongzhi.jpg",
        "tags": ["冬至", "蓝白"],
    },
    {
        "id": "asset_bg_mid_autumn",
        "name": "中秋背景",
        "source_path": "素材/节日节气海报/端午2.jpg",
        "file_name": "bg_mid_autumn.jpg",
        "tags": ["中秋", "团圆"],
    },
    {
        "id": "asset_bg_national_day",
        "name": "国庆背景",
        "source_path": "素材/节日节气海报/五一海报.jpg",
        "file_name": "bg_national_day.jpg",
        "tags": ["国庆", "红金"],
    },
    {
        "id": "asset_bg_double_11",
        "name": "双11背景",
        "source_path": "素材/节日节气海报/五一海报.jpg",
        "file_name": "bg_double_11.jpg",
        "tags": ["双11", "促销"],
    },
    {
        "id": "asset_bg_618",
        "name": "618背景",
        "source_path": "素材/节日节气海报/高考.jpg",
        "file_name": "bg_618.jpg",
        "tags": ["618", "科技蓝"],
    },
    {
        "id": "asset_bg_anniversary",
        "name": "周年庆背景",
        "source_path": "素材/节日节气海报/小满节气海报.jpg",
        "file_name": "bg_anniversary.jpg",
        "tags": ["周年庆", "庆典"],
    },
]
