from __future__ import annotations


MARKETING_NODES = [
    {
        "id": "node_spring_festival",
        "name": "春节",
        "type": "festival",
        "keywords": ["新春", "团圆", "健康水"],
        "colors": ["#C62828", "#F9D976"],
        "copy_direction": "新春祝福、健康饮水",
        "visual_direction": "红金喜庆氛围",
        "background_asset_id": "asset_bg_spring_festival",
    },
    {
        "id": "node_lantern_festival",
        "name": "元宵",
        "type": "festival",
        "keywords": ["团圆", "灯火", "安心饮水"],
        "colors": ["#B91C1C", "#FFE4B5"],
        "copy_direction": "团圆时刻、安心饮水",
        "visual_direction": "灯火团圆、暖色节庆",
        "background_asset_id": "asset_bg_lantern_festival",
    },
    {
        "id": "node_lichun",
        "name": "立春",
        "type": "solar_term",
        "keywords": ["春日", "焕新", "健康水"],
        "colors": ["#2E7D32", "#D8F3DC"],
        "copy_direction": "春日焕新、健康启程",
        "visual_direction": "清新绿色、春日生长",
        "background_asset_id": "asset_bg_lichun",
    },
    {
        "id": "node_lidong",
        "name": "立冬",
        "type": "solar_term",
        "keywords": ["冬日", "温暖", "健康水"],
        "colors": ["#D98A3B", "#F5E7D2"],
        "copy_direction": "温暖陪伴、健康饮水",
        "visual_direction": "暖色冬日氛围",
        "background_asset_id": "asset_bg_lidong",
    },
    {
        "id": "node_dongzhi",
        "name": "冬至",
        "type": "solar_term",
        "keywords": ["冬至", "团圆", "温暖守护"],
        "colors": ["#1D4ED8", "#F8FAFC"],
        "copy_direction": "冬至团圆、温暖守护",
        "visual_direction": "蓝白冬日、温暖光感",
        "background_asset_id": "asset_bg_dongzhi",
    },
    {
        "id": "node_mid_autumn",
        "name": "中秋",
        "type": "festival",
        "keywords": ["中秋", "团圆", "好水相伴"],
        "colors": ["#8B5E34", "#F6D365"],
        "copy_direction": "团圆佳节、好水相伴",
        "visual_direction": "月色团圆、金色质感",
        "background_asset_id": "asset_bg_mid_autumn",
    },
    {
        "id": "node_national_day",
        "name": "国庆",
        "type": "festival",
        "keywords": ["国庆", "欢庆", "健康生活"],
        "colors": ["#DC2626", "#FACC15"],
        "copy_direction": "欢庆假期、健康生活",
        "visual_direction": "红金庆典、明亮大气",
        "background_asset_id": "asset_bg_national_day",
    },
    {
        "id": "node_double_11",
        "name": "双11",
        "type": "promotion",
        "keywords": ["双11", "咨询", "智能净水"],
        "colors": ["#EF4444", "#FFEDD5"],
        "copy_direction": "节日咨询、智能净水方案",
        "visual_direction": "橙红促销、克制高级",
        "background_asset_id": "asset_bg_double_11",
    },
    {
        "id": "node_618",
        "name": "618",
        "type": "promotion",
        "keywords": ["618", "焕新", "净水方案"],
        "colors": ["#2563EB", "#DBEAFE"],
        "copy_direction": "年中焕新、净水方案咨询",
        "visual_direction": "科技蓝、清爽促销",
        "background_asset_id": "asset_bg_618",
    },
    {
        "id": "node_anniversary",
        "name": "周年庆",
        "type": "campaign",
        "keywords": ["周年", "感谢", "健康水专家"],
        "colors": ["#047857", "#FDE68A"],
        "copy_direction": "品牌感谢、健康水专家",
        "visual_direction": "环保绿、金色庆典",
        "background_asset_id": "asset_bg_anniversary",
    },
]


PRODUCTS = [
    {
        "id": "product_k2",
        "name": "名士K2智能直饮机",
        "model": "K2",
        "category": "商务直饮机",
        "short_description": "适合办公场景的智能直饮设备",
        "selling_points": ["智能直饮", "适配办公", "稳定供水"],
    },
    {
        "id": "product_h5",
        "name": "名士H5商务直饮机",
        "model": "H5",
        "category": "商务直饮机",
        "short_description": "适合会议、茶水间和公共办公区的商务饮水设备",
        "selling_points": ["商务场景", "多人饮水", "简洁易用"],
    },
    {
        "id": "product_p2",
        "name": "厨下净水器P2",
        "model": "P2",
        "category": "厨下净水器",
        "short_description": "适合家庭厨房的厨下净水解决方案",
        "selling_points": ["厨下安装", "家庭饮水", "日常烹饪"],
    },
]


COMPLIANCE_RULES = {
    "blocked_terms": [
        "最",
        "第一",
        "顶级",
        "绝对",
        "100%",
        "永久",
        "包治",
        "治愈",
        "疗效",
        "神效",
        "唯一",
        "国家级",
        "无敌",
        "根治",
    ],
    "suggestions": {
        "最": "建议改为“更”或删除绝对化表达",
        "第一": "建议改为“领先”并补充真实来源",
        "顶级": "建议改为“高品质”",
        "绝对": "建议改为“持续”或删除",
        "100%": "建议改为“充分”或给出可验证依据",
        "永久": "建议改为“长期”",
        "包治": "不得使用医疗功效承诺",
        "治愈": "不得使用医疗功效承诺",
        "疗效": "不得使用医疗功效暗示",
        "神效": "不得使用夸大功效表达",
        "唯一": "建议改为“可选”或删除",
        "国家级": "不得使用未经证明的权威背书",
        "无敌": "建议删除夸张化表达",
        "根治": "不得使用医疗功效承诺",
    },
}


SYSTEM_ASSET_SOURCES = [
    {
        "id": "asset_logo_original",
        "asset_type": "logo",
        "name": "PUDOW朴道原色Logo",
        "source": "system",
        "source_path": "素材/朴道logo/PUDOW朴道-原色.png",
        "file_name": "logo_original.png",
        "tags": ["PUDOW", "原色"],
    },
    {
        "id": "asset_logo_white",
        "asset_type": "logo",
        "name": "PUDOW朴道反白Logo",
        "source": "system",
        "source_path": "素材/朴道logo/PUDOW朴道-反白.png",
        "file_name": "logo_white.png",
        "tags": ["PUDOW", "反白"],
    },
    {
        "id": "asset_qrcode_wechat",
        "asset_type": "qrcode",
        "name": "朴道公众号二维码",
        "source": "system",
        "source_path": "素材/二维码汇总/朴道公众号二维码.jpg",
        "file_name": "qrcode_wechat.jpg",
        "tags": ["公众号"],
    },
    {
        "id": "asset_qrcode_video",
        "asset_type": "qrcode",
        "name": "朴道官方视频号二维码",
        "source": "system",
        "source_path": "素材/二维码汇总/朴道官方视频号二维码.png",
        "file_name": "qrcode_video.png",
        "tags": ["视频号"],
    },
    {
        "id": "asset_bottom_default",
        "asset_type": "bottom_bar",
        "name": "默认底部宣传条",
        "source": "system",
        "source_path": "素材/asset/素材整理/节日节气海报/底部宣传图.jpg",
        "file_name": "bottom_bar_default.jpg",
        "tags": ["默认", "品牌"],
    },
]


BACKGROUND_SOURCES = [
    {
        "id": "asset_bg_spring_festival",
        "name": "春节背景",
        "source_path": "素材/节日节气海报/除夕海报.jpg",
        "file_name": "bg_spring_festival.jpg",
        "tags": ["春节", "红金"],
    },
    {
        "id": "asset_bg_lantern_festival",
        "name": "元宵背景",
        "source_path": "素材/节日节气海报/元旦海报.jpg",
        "file_name": "bg_lantern_festival.jpg",
        "tags": ["元宵", "节庆"],
    },
    {
        "id": "asset_bg_lichun",
        "name": "立春背景",
        "source_path": "素材/节日节气海报/小满节气海报.jpg",
        "file_name": "bg_lichun.jpg",
        "tags": ["立春", "绿色"],
    },
    {
        "id": "asset_bg_lidong",
        "name": "立冬背景",
        "source_path": "素材/节日节气海报/端午2.jpg",
        "file_name": "bg_lidong.jpg",
        "tags": ["立冬", "暖色"],
    },
    {
        "id": "asset_bg_dongzhi",
        "name": "冬至背景",
        "source_path": "素材/节日节气海报/元旦海报.jpg",
        "file_name": "bg_dongzhi.jpg",
        "tags": ["冬至", "蓝白"],
    },
    {
        "id": "asset_bg_mid_autumn",
        "name": "中秋背景",
        "source_path": "素材/节日节气海报/端午2.jpg",
        "file_name": "bg_mid_autumn.jpg",
        "tags": ["中秋", "团圆"],
    },
    {
        "id": "asset_bg_national_day",
        "name": "国庆背景",
        "source_path": "素材/节日节气海报/五一海报.jpg",
        "file_name": "bg_national_day.jpg",
        "tags": ["国庆", "红金"],
    },
    {
        "id": "asset_bg_double_11",
        "name": "双11背景",
        "source_path": "素材/节日节气海报/五一海报.jpg",
        "file_name": "bg_double_11.jpg",
        "tags": ["双11", "促销"],
    },
    {
        "id": "asset_bg_618",
        "name": "618背景",
        "source_path": "素材/节日节气海报/高考.jpg",
        "file_name": "bg_618.jpg",
        "tags": ["618", "科技蓝"],
    },
    {
        "id": "asset_bg_anniversary",
        "name": "周年庆背景",
        "source_path": "素材/节日节气海报/小满节气海报.jpg",
        "file_name": "bg_anniversary.jpg",
        "tags": ["周年庆", "庆典"],
    },
]
